### PR TITLE
Generalize rotation

### PR DESCRIPTION
**Pull request by jrekoske-usgs**
A new rotation module provides two functions:
- rotate_pick_method(), which allows for GMRotD, Arithmetic mean, or Max
- rotate(), which returns an array of the rotated traces. Trace can be combined or kept separate.

gmrotd.py has been changed to call the general rotation method picker.

### CODE REVIEW

**Comment by emthompson-usgs** [comment]
It looks like the tests exercise the code but do not check the result. Could you check the result against values computed from independent code?

**Comment by emthompson-usgs** [comment]
A few other things I didn't notice before: 
 - Rather than issue a warning and return nothing when an invalid method is requested, I think it should raise an exception. 
 - The supported values of `method_pick` should be documented in docstrings (which would also include other standard things like argument definitions, types, and a general description of what the method does.)

**Comment by jrekoske-usgs** [comment]
I've made the following modifications given the suggestions from Eric and Heather:
- Rotation test compares with RotD50 calculations from independent code.
- Changed warning to exception, and added more exception handling.
- Added docstring for the general rotation method (now called get_max)
- Trace 2 is now optional (defaulted to None) so that the maximum method can be done with only one trace.
- get_max pick and rotate are now separate (necessary for Arias intensity), so that the get_max can either be used on 1D traces, or on 2D matrixes of rotated data.  This requires checking the shape of the input arrays.

**Comment by hschovanec-usgs** [comment]
Testing some things now. Holding off on merging until spectral amplitudes match as we discussed.

**Comment by emthompson-usgs** [comment]
It is nice how you made this so that it can achieve a few different tasks in an efficient way. A few things:

 - In the `get_max` docstrings I think it would be good to explain what the 2D case is a little more clearly. The phrase "a 2d rotated matrix" is a little vague to me and it took me a little time looking over the code to realize what this meant. I think it needs to be a 2D array where the number of rows is the number of traces, and the number of columns is the number of samples in the trace. Additionally, I think this method assumes 
    1) that the rows in each matrix are the same component at different rotation angles, 
    2) if `tr2` is provided, the orientation of the trace in each row is orthogonal to the analogous row in `tr1`, and 
    3) the traces that constitute `tr1` and `tr2` are both horizontal components.

   Perhaps spell that out clearly in the main text, and then in the argument definitions, just say "2d matrix of rotated components" rather than "2d rotation matrix" (the latter phrase could be mistaken to be something else).

- It looks like when the picked peak is the max, then it handles the case for when `tr2` is None, but this case is not handled for the arithmetic or geometric means. Since these cases don't really make sense, it may be best to raise an exception up front if one of the means is requested but `tr2` is None. 

- It would be nice to add an argument to `rotate` for the delta degrees. The default can be one, which is currently hard coded. Also, the docstring defines some arguments that do not exist for this method (percentiles, geo_mean, etc.).

**Comment by jrekoske-usgs** [comment]
These suggestions have all been incorporated into my pull request. In addition, the calculations have been verified using a single-record and are within 0.5% difference from Steven's calculations. Further validation will be done through #87 .

**Comment by jrekoske-usgs** [comment]
- Fixed build error (station summary only rotates when told to do so.)
- Changed 9.8 to the scipy g constant.
- Adjusted tolerances for some assertions due to accuracy errors from new g constant.

**Pull request merged**
